version: '3.8'

volumes:
  db: {}
  rabbit: {}

services:
  db:
    image: kartoza/postgis:12.0
    volumes:
      - db:/var/lib/postgresql
      - ./db/init.sql:/docker-entrypoint-initdb.d/setup-db.sql
    environment:
      - POSTGRES_USER=libretaxi
      - POSTGRES_PASSWORD=libretaxi
      - POSTGRES_DB=libretaxi
      - POSTGRES_TEMPLATE_EXTENSIONS=true
      - POSTGRES_PASS=libretaxi
      - POSTGRES_DBNAME=libretaxi
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
    ports:
      - 127.0.0.1:15432:5432
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq-libretaxi
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
