-- Add PostGIS extension if not exists
CREATE EXTENSION IF NOT EXISTS postgis;

-- Create users table if not exists
CREATE TABLE IF NOT EXISTS users (
    "userId" BIGINT NOT NULL,
    "menuId" INT,
    "username" TEXT,
    "firstName" TEXT,
    "lastName" TEXT,
    "lon" DOUBLE PRECISION,
    "lat" DOUBLE PRECISION,
    "geog" GEOGRAPHY(POINT, 4326),
    "languageCode" TEXT,
    "reportCnt" INT DEFAULT 0,
    "shadowBanned" BOOLEAN DEFAULT FALSE,
    "createdAtUtc" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
    PRIMARY KEY ("userId")
);

-- Create spatial index on users table if not exists
CREATE INDEX IF NOT EXISTS users_geog_idx ON users USING GIST(geog);

-- Create posts table if not exists
CREATE TABLE IF NOT EXISTS posts (
    "postId" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" BIGINT NOT NULL REFERENCES users("userId"),
    "text" TEXT,
    "lon" DOUBLE PRECISION,
    "lat" DOUBLE PRECISION,
    "geog" GEOGRAPHY(POINT, 4326),
    "reportCnt" INT DEFAULT 0,
    "createdAtUtc" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc')
);

-- Create indices on posts table if not exist
CREATE INDEX IF NOT EXISTS idx_created_at_utc_posts ON posts("createdAtUtc");
CREATE INDEX IF NOT EXISTS idx_user_id_and_created_at_utc ON posts("userId", "createdAtUtc");

-- Create dismissed_feature_callouts table if not exists
CREATE TABLE IF NOT EXISTS dismissed_feature_callouts (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" BIGINT NOT NULL, -- Do not reference users table to allow usage when user isn't present
    "featureName" TEXT NOT NULL,
    "createdAtUtc" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() AT TIME ZONE 'utc'),
    UNIQUE ("userId", "featureName")
);

-- Create index on dismissed_feature_callouts table if not exists
CREATE INDEX IF NOT EXISTS idx_user_id_at_dismissed_feature_callouts ON dismissed_feature_callouts("userId");

-- Create or recreate libretaxi role if not exists
DO $$ BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'libretaxi') THEN
        CREATE ROLE libretaxi WITH LOGIN PASSWORD 'libretaxi';
    END IF;
END $$;
